-- 코드를 입력하세요
SELECT ANIMAL_OUTS.ANIMAL_ID , ANIMAL_OUTS.NAME
FROM ANIMAL_OUTS 
LEFT JOIN ANIMAL_INS 
ON ANIMAL_OUTS.ANIMAL_ID = ANIMAL_INS.ANIMAL_ID
WHERE ANIMAL_INS.ANIMAL_ID IS NULL

# SELECT A.ANIMAL_ID, A.NAME
# FROM ANIMAL_OUTS AS A
# LEFT OUTER JOIN ANIMAL_INS AS B
# ON A.ANIMAL_ID=B.ANIMAL_ID
# where B.ANIMAL_ID IS NULL;