SELECT c.CAR_ID, c.CAR_TYPE, ROUND(c.DAILY_FEE*30*(1-d.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c, CAR_RENTAL_COMPANY_DISCOUNT_PLAN d
WHERE c.CAR_TYPE = d.CAR_TYPE
    AND c.CAR_TYPE IN ('세단', 'SUV') 
    AND d.DURATION_TYPE = '30일 이상'
    AND c.DAILY_FEE*30*(1-DISCOUNT_RATE/100) >= 500000 AND c.DAILY_FEE*30*(1-DISCOUNT_RATE/100) < 2000000
    AND NOT c.CAR_ID IN (
        SELECT h.CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY h       
        WHERE h.END_DATE >= 20221101)
GROUP BY c.CAR_ID
ORDER BY c.DAILY_FEE*30*(1-(DISCOUNT_RATE/100)) DESC, c.CAR_TYPE, c.CAR_ID DESC
