SELECT DATE_FORMAT(o.SALES_DATE, '%Y') 'YEAR', 
       DATE_FORMAT(o.SALES_DATE, '%m') 'MONTH', 
       COUNT(DISTINCT(o.USER_ID)) 'PUCHASED_USERS',
       ROUND(COUNT(DISTINCT(o.USER_ID)) / (SELECT COUNT(DISTINCT(u.USER_ID)) FROM USER_INFO u WHERE DATE_FORMAT(u.JOINED, '%Y') = 2021), 1) 'PUCHASED_RATIO'
FROM ONLINE_SALE o, USER_INFO u
WHERE o.USER_ID = u.USER_ID and DATE_FORMAT(u.JOINED, '%Y') = 2021
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH