-- 코드를 입력하세요
SELECT A.TITLE,A.BOARD_ID,B.REPLY_ID,B.WRITER_ID,B.CONTENTS, DATE_FORMAT(B.CREATED_DATE,'%Y-%m-%d') AS CREATED_DATE
from USED_GOODS_BOARD as A
inner join USED_GOODS_REPLY as B
on A.BOARD_ID = B.BOARD_ID
where DATE_FORMAT(A.CREATED_DATE, '%Y-%m') = '2022-10'order by B.CREATED_DATE ASC, A.TITLE ASC