-- 코드를 입력하세요
SELECT WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS,coalesce(FREEZER_YN,'N') as FREEZER_YN
    from FOOD_WAREHOUSE
    where WAREHOUSE_NAME like '%경기%'
    order by WAREHOUSE_ID

# WAREHOUSE_ID,WAREHOUSE_NAME,ADDRESS,TLNO,FREEZER_YN