-- 코드를 입력하세요
# SELECT A.ANIMAL_ID , A.NAME
# FROM ANIMAL_OUTS AS A
# LEFT JOIN ANIMAL_INS AS B 
# ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE A.DATETIME > B.DATETIME
# ORDER BY A.DATETIME

SELECT INS.ANIMAL_ID , INS.NAME
FROM ANIMAL_INS AS INS 
JOIN ANIMAL_OUTS AS OUTS
ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
WHERE INS.DATETIME > OUTS.DATETIME 
ORDER BY INS.DATETIME